name: deploy-static

on:
  push:
    branches: [master]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  secrets-gate:
    runs-on: ubuntu-latest
    outputs:
      ok: ${{ steps.check-secrets.outputs.ok }}
    steps:
      - name: check for secrets needed to run workflows
        id: check-secrets
        run: |
          if [ ${{ secrets.STATIC_BUILD_ENABLED }} == 'true' ]; then
            echo "ok=enabled" >> $GITHUB_OUTPUT
          fi
  build:
    needs:
      - secrets-gate
    if: ${{ needs.secrets-gate.outputs.ok == 'enabled'}}
    environment:
      name: '${{ github.repository }}-static-build-gh-pages'
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: lowercase github.repository
        run: |
          echo "REPO_NAME=`echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]'`" >>${GITHUB_ENV}
      - name: Checkout Infinite Reality Engine
        uses: actions/checkout@v3
        with:
          repository: ir-engine/ir-engine
          ref: dev
      - name: Checkout Project
        uses: actions/checkout@v3
        with:
          path: './packages/projects/projects/${{ env.REPO_NAME }}'
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
      - name: restore lerna
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            */*/node_modules
            package-lock.json
          key: ${{ runner.os }}-branch-build-${{ hashFiles('**/package.json') }}
      - run: cp .env.local.default .env.local
      - run: mkdir -p packages/projects/projects/ir-engine/default-project && cp -r packages/projects/default-project/. packages/projects/projects/ir-engine/default-project
      - run: npm install --production=false --loglevel notice
      - run: cd './packages/projects/projects/${{ env.REPO_NAME }}' && npx cross-env STATIC_BUILD_HOST=${{ secrets.STATIC_BUILD_HOST }} npm run build
      - name: Sleep for 15 seconds
        run: sleep 15s
        shell: bash
      - name: Netlify Deploy
        uses: jsmrcaga/action-netlify-deploy@v2.4.0
        with:
          build_directory: './packages/projects/projects/${{ env.REPO_NAME }}/dist'
          install_command: "echo Skipping installing the dependencies"
          build_command: "echo Skipping building the web files"
          monorepo_package: "@${{ env.REPO_NAME }}"
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_MESSAGE: "Deployed from GitHub action"
          NETLIFY_DEPLOY_TO_PROD: true


