name: project-build
on:
  pull_request:
    branches: [dev]
  push:
    branches: [dev]
jobs:
  secrets-gate:
    runs-on: ubuntu-latest
    outputs:
      ok: ${{ steps.check-secrets.outputs.ok }}
      repo: ${{ steps.repo-lowercase.outputs.repo }}
    steps:
      - name: check for secrets needed to run workflows
        id: check-secrets
        run: |
          if [ ${{ secrets.BRANCH_BUILD_ENABLED }} == 'true' ]; then
            echo "ok=enabled" >> $GITHUB_OUTPUT
          fi
      - name: get lowercase repo name
        id: repo-lowercase
        run: |
          echo "repo=`echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]'`" >> $GITHUB_OUTPUT

  install-modules:
    needs:
      - secrets-gate
    if: ${{ needs.secrets-gate.outputs.ok == 'enabled' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: lowercase github.repository
        run: |
          echo "REPO_NAME=`echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]'`" >>${GITHUB_ENV}
      - name: Set the branch name
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "BRANCH_NAME=${{ github.head_ref }}" >> $GITHUB_ENV
          else
            echo "BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_ENV
          fi

      - name: Fetch branches from enchantmentengine
        run: |
          git ls-remote --heads https://github.com/enchantmentengine/enchantmentengine.git | awk -F'/' '{print $3}' > engine-branches.txt

      - name: Check if current branch exists in enchantmentengine
        run: |
          if grep -q "^${{ env.BRANCH_NAME }}$" engine-branches.txt; then
            echo "Branch '${{ env.BRANCH_NAME }}' exists in enchantmentengine."
            echo "checkout_branch=${{ env.BRANCH_NAME }}" >> $GITHUB_ENV
          else
            echo "Branch '${{ env.BRANCH_NAME }}' does not exist in enchantmentengine. Using 'dev' branch."
            echo "checkout_branch=dev" >> $GITHUB_ENV
          fi

      - name: Checkout Infinite Reality Engine
        uses: actions/checkout@v3
        with:
          repository: enchantmentengine/enchantmentengine
          ref: ${{ env.checkout_branch }}

      - name: Checkout Project
        uses: actions/checkout@v3
        with:
          path: './packages/projects/projects/${{ needs.secrets-gate.outputs.repo }}'
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
      - name: restore lerna
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            */*/node_modules
            package-lock.json
          key: ${{ runner.os }}-project-build-${{ hashFiles('**/package.json') }}
      - run: cp .env.local.default .env.local
      - run: sed -i 's/localhost/127.0.0.1/g' .env.local
      - name: Config npm registry token
        run: npm config set '//npm.pkg.github.com/:_authToken' "${NPM_TOKEN}"
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm install --loglevel notice
      - name: cache for next steps
        uses: actions/cache@v3
        with:
          path: .
          key: dir-${{github.sha}}

  check-lint-and-errors:
    needs:
      - secrets-gate
      - install-modules
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/cache@v3
        with:
          path: .
          key: dir-${{github.sha}}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
      - run: mkdir -p ./packages/projects/projects/enchantmentengine && cp -r ./packages/projects/default-project ./packages/projects/projects/enchantmentengine/default-project
      - run: npm install --loglevel notice
      - run: npx lerna run --scope '@${{ needs.secrets-gate.outputs.repo }}' lint
      - run: npx lerna run --scope '@${{ needs.secrets-gate.outputs.repo }}' check-errors
        timeout-minutes: 20

  test:
    needs:
      - secrets-gate
      - install-modules
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/cache@v3
        with:
          path: .
          key: dir-${{github.sha}}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
      - run: npm run dev-docker
      - run: npm run dev-reinit
      - run: npx cross-env TEST=true npx lerna run --scope '@${{ needs.secrets-gate.outputs.repo }}' test
        env:
          TEST: true